# frozen_string_literal: true

require_relative 'require_app'
require_app

def mbti_orm = TravellingSuggestions::Database::MBTIOrm

mbti_orm.create(question: 'WHEN YOU GO SOMEWHERE FOR THE DAY, WOULD YOU RATHER',
                answerA: 'PLAN WHAT YOU WILL DO AND WHEN',
                answerB: 'JUST GO!!',
                section: 'JP', directionA: 'J', scoreA: 2, scoreB: 2)
mbti_orm.create(question: 'IF YOU WERE A TEACHER, WOULD YOU RATHER TEACH',
                answerA: 'FACTS-BASED COURSES',
                answerB: 'COURSES INVOLVING OPINION OR THEORY',
                section: 'SN', directionA: 'S', scoreA: 2, scoreB: 2)
mbti_orm.create(question: 'ARE YOU USUALLY',
                answerA: 'A "GOOD MIXER" WITH GROUPS OF PEOPLE',
                answerB: 'ATHER QUIET AND RESERVED',
                section: 'EI', directionA: 'E', scoreA: 2, scoreB: 2)
mbti_orm.create(question: 'DO YOU MORE OFTEN LET',
                answerA: 'YOUR HEART RULE YOUR HEAD',
                answerB: 'YOUR HEAD RULE YOUR HEART',
                section: 'TF', directionA: 'F', scoreA: 1, scoreB: 2)
mbti_orm.create(question: 'IN DOING SOMETHING THAT MANY OTHER PEOPLE DO, WOULD YOU RATHER',
                answerA: 'INVENT A WAY OF YOUR OWN',
                answerB: 'DO IT IN THE ACCEPTED WAY',
                section: 'SN', directionA: 'N', scoreA: 1, scoreB: 1)
mbti_orm.create(question: 'AMONG YOUR FRIENDS ARE YOU',
                answerA: 'FULL OF NEWS ABOUT EVERYBODY',
                answerB: 'ONE OF THE LAST TO HEAR WHAT IS GOING ON',
                section: 'EI', directionA: 'E', scoreA: 2, scoreB: 1)
mbti_orm.create(question: 'DOES THE IDEA OF MAKING A LIST OF WHAT YOU SHOULD GET DONE OVER A WEEKEND',
                answerA: 'HELP YOU',
                answerB: 'STRESS YOU, OR POSITIVELY DEPRESS YOU',
                section: 'JP', directionA: 'J', scoreA: 1, scoreB: 1)
mbti_orm.create(question: 'WHEN YOU HAVE A SPECIAL JOB TO DO, DO YOU LIKE TO',
                answerA: 'ORGANIZE IT CAREFULLY BEFORE YOU START',
                answerB: 'FIND OUT WHAT IS NECESSARY AS YOU GO ALONG',
                section: 'JP', directionA: 'J', scoreA: 1, scoreB: 2)
mbti_orm.create(question: 'DO YOU TEND TO HAVE',
                answerA: 'BROAD FRIENDSHIPS WITH MANY DIFFERENT PEOPLE',
                answerB: 'DEEP FRIENDSHIP WITH VERY FEW PEOPLE',
                section: 'EI', directionA: 'E', scoreA: 2, scoreB: 1)

                mbti_orm.create(question: 'ARE YOU USUALLY',
                answerA: 'A "GOOD MIXER" WITH GROUPS OF PEOPLE',
                answerB: 'ATHER QUIET AND RESERVED',
                section: 'EI', directionA: 'E', scoreA: 2, scoreB: 2)mbti_orm.create(question: 'ARE YOU USUALLY',
                answerA: 'A "GOOD MIXER" WITH GROUPS OF PEOPLE',
                answerB: 'ATHER QUIET AND RESERVED',
                section: 'EI', directionA: 'E', scoreA: 2, scoreB: 2)mbti_orm.create(question: 'ARE YOU USUALLY',
                answerA: 'A "GOOD MIXER" WITH GROUPS OF PEOPLE',
                answerB: 'ATHER QUIET AND RESERVED',
                section: 'EI', directionA: 'E', scoreA: 2, scoreB: 2)mbti_orm.create(question: 'ARE YOU USUALLY',
                answerA: 'A "GOOD MIXER" WITH GROUPS OF PEOPLE',
                answerB: 'ATHER QUIET AND RESERVED',
                section: 'EI', directionA: 'E', scoreA: 2, scoreB: 2)mbti_orm.create(question: 'ARE YOU USUALLY',
                answerA: 'A "GOOD MIXER" WITH GROUPS OF PEOPLE',
                answerB: 'ATHER QUIET AND RESERVED',
                section: 'EI', directionA: 'E', scoreA: 2, scoreB: 2)mbti_orm.create(question: 'ARE YOU USUALLY',
                answerA: 'A "GOOD MIXER" WITH GROUPS OF PEOPLE',
                answerB: 'ATHER QUIET AND RESERVED',
                section: 'EI', directionA: 'E', scoreA: 2, scoreB: 2)mbti_orm.create(question: 'ARE YOU USUALLY',
                answerA: 'A "GOOD MIXER" WITH GROUPS OF PEOPLE',
                answerB: 'ATHER QUIET AND RESERVED',
                section: 'EI', directionA: 'E', scoreA: 2, scoreB: 2)mbti_orm.create(question: 'ARE YOU USUALLY',
                answerA: 'A "GOOD MIXER" WITH GROUPS OF PEOPLE',
                answerB: 'ATHER QUIET AND RESERVED',
                section: 'EI', directionA: 'E', scoreA: 2, scoreB: 2)mbti_orm.create(question: 'ARE YOU USUALLY',
                answerA: 'A "GOOD MIXER" WITH GROUPS OF PEOPLE',
                answerB: 'ATHER QUIET AND RESERVED',
                section: 'EI', directionA: 'E', scoreA: 2, scoreB: 2)mbti_orm.create(question: 'ARE YOU USUALLY',
                answerA: 'A "GOOD MIXER" WITH GROUPS OF PEOPLE',
                answerB: 'ATHER QUIET AND RESERVED',
                section: 'EI', directionA: 'E', scoreA: 2, scoreB: 2)mbti_orm.create(question: 'ARE YOU USUALLY',
                answerA: 'A "GOOD MIXER" WITH GROUPS OF PEOPLE',
                answerB: 'ATHER QUIET AND RESERVED',
                section: 'EI', directionA: 'E', scoreA: 2, scoreB: 2)mbti_orm.create(question: 'ARE YOU USUALLY',
                answerA: 'A "GOOD MIXER" WITH GROUPS OF PEOPLE',
                answerB: 'ATHER QUIET AND RESERVED',
                section: 'EI', directionA: 'E', scoreA: 2, scoreB: 2)mbti_orm.create(question: 'ARE YOU USUALLY',
                answerA: 'A "GOOD MIXER" WITH GROUPS OF PEOPLE',
                answerB: 'ATHER QUIET AND RESERVED',
                section: 'EI', directionA: 'E', scoreA: 2, scoreB: 2)mbti_orm.create(question: 'ARE YOU USUALLY',
                answerA: 'A "GOOD MIXER" WITH GROUPS OF PEOPLE',
                answerB: 'ATHER QUIET AND RESERVED',
                section: 'EI', directionA: 'E', scoreA: 2, scoreB: 2)mbti_orm.create(question: 'ARE YOU USUALLY',
                answerA: 'A "GOOD MIXER" WITH GROUPS OF PEOPLE',
                answerB: 'ATHER QUIET AND RESERVED',
                section: 'EI', directionA: 'E', scoreA: 2, scoreB: 2)mbti_orm.create(question: 'ARE YOU USUALLY',
                answerA: 'A "GOOD MIXER" WITH GROUPS OF PEOPLE',
                answerB: 'ATHER QUIET AND RESERVED',
                section: 'EI', directionA: 'E', scoreA: 2, scoreB: 2)mbti_orm.create(question: 'ARE YOU USUALLY',
                answerA: 'A "GOOD MIXER" WITH GROUPS OF PEOPLE',
                answerB: 'ATHER QUIET AND RESERVED',
                section: 'EI', directionA: 'E', scoreA: 2, scoreB: 2)mbti_orm.create(question: 'ARE YOU USUALLY',
                answerA: 'A "GOOD MIXER" WITH GROUPS OF PEOPLE',
                answerB: 'ATHER QUIET AND RESERVED',
                section: 'EI', directionA: 'E', scoreA: 2, scoreB: 2)mbti_orm.create(question: 'ARE YOU USUALLY',
                answerA: 'A "GOOD MIXER" WITH GROUPS OF PEOPLE',
                answerB: 'ATHER QUIET AND RESERVED',
                section: 'EI', directionA: 'E', scoreA: 2, scoreB: 2)mbti_orm.create(question: 'ARE YOU USUALLY',
                answerA: 'A "GOOD MIXER" WITH GROUPS OF PEOPLE',
                answerB: 'ATHER QUIET AND RESERVED',
                section: 'EI', directionA: 'E', scoreA: 2, scoreB: 2)mbti_orm.create(question: 'ARE YOU USUALLY',
                answerA: 'A "GOOD MIXER" WITH GROUPS OF PEOPLE',
                answerB: 'ATHER QUIET AND RESERVED',
                section: 'EI', directionA: 'E', scoreA: 2, scoreB: 2)mbti_orm.create(question: 'ARE YOU USUALLY',
                answerA: 'A "GOOD MIXER" WITH GROUPS OF PEOPLE',
                answerB: 'ATHER QUIET AND RESERVED',
                section: 'EI', directionA: 'E', scoreA: 2, scoreB: 2)mbti_orm.create(question: 'ARE YOU USUALLY',
                answerA: 'A "GOOD MIXER" WITH GROUPS OF PEOPLE',
                answerB: 'ATHER QUIET AND RESERVED',
                section: 'EI', directionA: 'E', scoreA: 2, scoreB: 2)mbti_orm.create(question: 'ARE YOU USUALLY',
                answerA: 'A "GOOD MIXER" WITH GROUPS OF PEOPLE',
                answerB: 'ATHER QUIET AND RESERVED',
                section: 'EI', directionA: 'E', scoreA: 2, scoreB: 2)mbti_orm.create(question: 'ARE YOU USUALLY',
                answerA: 'A "GOOD MIXER" WITH GROUPS OF PEOPLE',
                answerB: 'ATHER QUIET AND RESERVED',
                section: 'EI', directionA: 'E', scoreA: 2, scoreB: 2)